
async function contentLocksPage(){
  const state={groupId:localStorage.getItem("pbs_lock_group")||"",groups:[],rules:[],settings:null,exceptions:[],domains:[],logsPage:1,logType:"",logQ:"",logFrom:"",logTo:"",tab:"links"};
  const actorId=()=>localStorage.getItem("pbs_actor_id")||"PANEL_OWNER";
  const faDate=v=>v?new Date(v).toLocaleString("fa-IR",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}):"—";
  const escLock=v=>typeof esc==="function"?esc(v):String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
  async function api(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};const r=await fetch(path,{cache:"no-store",...options,headers}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"عملیات ناموفق بود");return d;}
  function toast(message,kind="ok"){let b=document.getElementById("contentLockToast");if(!b){b=document.createElement("div");b.id="contentLockToast";b.className="content-lock-toast";document.body.appendChild(b);}b.textContent=message;b.className="content-lock-toast "+kind+" show";clearTimeout(b._t);b._t=setTimeout(()=>b.classList.remove("show"),3000);}
  const sections={
    links:{label:"لینک و تبلیغات",icon:"↗",desc:"کنترل لینک‌ها، تبلیغات و دامنه‌های مجاز"},
    media:{label:"رسانه",icon:"◈",desc:"قفل عکس، ویدیو، موزیک، GIF، استیکر و صدا"},
    forwarding:{label:"فوروارد و اشتراک‌گذاری",icon:"⇱",desc:"کنترل منبع فوروارد و اشتراک‌گذاری پیام"},
    files:{label:"فایل و سند",icon:"▤",desc:"پسوند، حجم و انواع فایل قابل ارسال"},
    messages:{label:"پیام",icon:"≡",desc:"طول پیام، نرخ ارسال و محدودیت‌های متنی"},
    interactions:{label:"تعامل و ویرایش",icon:"✎",desc:"ریپلای، ویرایش، هشتگ، منشن و پیش‌نمایش"},
    anti_attack:{label:"ضد اتک",icon:"◇",desc:"ضد فلود، تکرار، هجوم لینک و رسانه"},
    advanced:{label:"محتوای پیشرفته",icon:"◆",desc:"Contact، Location، Poll، Game و Web App"},
    exceptions:{label:"استثناها",icon:"◌",desc:"اعضای معاف، نقش‌ها و منابع مجاز"},
    logs:{label:"لاگ‌ها",icon:"▥",desc:"ردیابی کامل حذف و انسداد"},
    tester:{label:"تستر قوانین",icon:"⌁",desc:"قبل از فعال‌سازی، قانون‌ها را آزمایش کنید"}
  };
  const groupLabel=g=>(g.title||g.username)?((g.title||"گروه")+(g.username?" · @"+g.username:"")):String(g.id);
  const getRule=k=>state.rules.find(r=>r.rule_key===k);
  const cfg=k=>getRule(k)?.config||{};
  const isOn=k=>!!getRule(k)?.enabled;
  const actionOptions=(v="delete")=>[["delete","فقط حذف"],["delete_notify","حذف + اخطار"],["delete_mute","حذف + سکوت"],["delete_ban","حذف + اخراج موقت"]].map(x=>'<option value="'+x[0]+'" '+(x[0]===v?"selected":"")+'>'+x[1]+'</option>').join("");
  function ruleCard(r,extra=""){return'<div class="lock-rule-card"><div class="lock-rule-main"><label class="lock-switch"><input type="checkbox" data-lock-toggle="'+r.rule_key+'" '+(r.enabled?"checked":"")+'><span></span></label><div><b>'+escLock(r.title)+'</b><small>'+escLock(r.description)+'</small></div></div>'+extra+'<span class="lock-rule-key">'+escLock(r.rule_key)+'</span></div>';}
  function numberField(k,name,value,min=0,max=100000,unit=""){return'<label class="lock-field">'+name+'<div><input data-lock-field="'+k+'" data-config="'+name+'" type="number" min="'+min+'" max="'+max+'" value="'+escLock(value??"")+'">'+(unit?'<em>'+unit+'</em>':"")+'</div></label>';}
  function renderGroups(){const s=document.getElementById("contentLockGroupSelect");s.innerHTML='<option value="">انتخاب گروه هدف...</option>'+state.groups.map(g=>'<option value="'+escLock(g.id)+'">'+escLock(groupLabel(g))+' · '+escLock(g.id)+'</option>').join("");if(state.groupId&&!state.groups.some(g=>String(g.id)===String(state.groupId)))s.innerHTML+='<option value="'+escLock(state.groupId)+'" selected>شناسه دستی · '+escLock(state.groupId)+'</option>';s.value=state.groupId||"";document.getElementById("contentLockEmptyGroup").style.display=state.groups.length?"none":"block";}
  async function loadGroups(){try{state.groups=(await api("/api/content-locks/groups")).groups||[];}catch{state.groups=[];}renderGroups();}
  async function selectGroup(id){id=String(id||"").trim();if(!/^-?[0-9]+$/.test(id)||id==="0"){toast("شناسه گروه معتبر نیست.","error");return;}state.groupId=id;state.logsPage=1;localStorage.setItem("pbs_lock_group",id);document.getElementById("contentLockGroupId").value=id;document.getElementById("contentLockGroupSelect").value=id;await loadAll();}
  async function loadAll(){if(!state.groupId){renderStats(null);renderTab();return;}try{const[o,r,e,d]=await Promise.all([api("/api/content-locks/overview?group_id="+encodeURIComponent(state.groupId)),api("/api/content-locks/rules?group_id="+encodeURIComponent(state.groupId)),api("/api/content-locks/exceptions?group_id="+encodeURIComponent(state.groupId)),api("/api/content-locks/domains?group_id="+encodeURIComponent(state.groupId))]);state.settings=o.settings;state.rules=r.rules||[];state.exceptions=e.exceptions||[];state.domains=d.domains||[];renderStats(o.stats);renderTab();}catch(e){toast(e.message,"error");}}
  function renderStats(s){const a=s||{};document.getElementById("lockActiveRules").textContent=a.activeRules??0;document.getElementById("lockBlockedToday").textContent=a.blockedToday??0;document.getElementById("lockExceptionsCount").textContent=a.exceptions??0;document.getElementById("lockSystemState").textContent=state.settings?.enabled===false?"خاموش":"فعال";document.getElementById("lockSystemState").className="lock-status-value "+(state.settings?.enabled===false?"off":"on");document.getElementById("contentLockEnabled").checked=state.settings?.enabled!==false;}
  async function saveRule(key,enabled,patch){const old=getRule(key);try{await api("/api/content-locks/rules/"+encodeURIComponent(key),{method:"PUT",body:JSON.stringify({group_id:state.groupId,enabled,config:{...(old?.config||{}),...(patch||{})},actor_id:actorId()})});if(old){old.enabled=enabled;old.config={...(old.config||{}),...(patch||{})};}toast("قانون ذخیره شد.");renderTab();}catch(e){toast(e.message,"error");}}
  async function toggleRule(input){await saveRule(input.dataset.lockToggle,input.checked,{});}
  async function saveConfigRow(key,fields){const r=getRule(key);const patch={...(r?.config||{})};Object.keys(fields).forEach(k=>patch[k]=fields[k]);await saveRule(key,r?.enabled===true,patch);}
  function shellBody(){return'<div class="content-lock-hero"><div><span class="eyebrow">GROUP MANAGEMENT · CAPABILITY 13 / 60</span><h1>سیستم قفل و کنترل محتوا</h1><p>کنترل یکپارچه محتوا، تعامل، اشتراک‌گذاری و رفتارهای مشکوک در گروه با قوانین قابل تنظیم و لاگ کامل.</p></div><div class="content-lock-hero-actions"><div class="lock-group-picker"><label>گروه هدف<select id="contentLockGroupSelect"><option value="">در حال دریافت...</option></select></label><div><input id="contentLockGroupId" inputmode="numeric" placeholder="شناسه گروه (-100...)" value="'+escLock(state.groupId)+'"><button class="ghost" id="applyContentLockGroup">اعمال</button></div></div><label class="lock-master-toggle"><span><b>سیستم قفل محتوا</b><small>فعال‌سازی مرکزی تمام قوانین</small></span><i class="lock-switch"><input id="contentLockEnabled" type="checkbox"><span></span></i></label></div></div><div class="stats content-lock-stats"><div class="stat-card"><div class="stat-top"><span class="stat-icon gold">◇</span><span class="stat-kicker">ACTIVE RULES</span></div><strong id="lockActiveRules">0</strong><span>قوانین فعال</span></div><div class="stat-card"><div class="stat-top"><span class="stat-icon gold">⊘</span><span class="stat-kicker">BLOCKED · TODAY</span></div><strong id="lockBlockedToday">0</strong><span>پیام‌های مسدودشده امروز</span></div><div class="stat-card"><div class="stat-top"><span class="stat-icon gold">◌</span><span class="stat-kicker">EXCEPTIONS</span></div><strong id="lockExceptionsCount">0</strong><span>استثناهای فعال</span></div><div class="stat-card"><div class="stat-top"><span class="stat-icon gold">●</span><span class="stat-kicker">SYSTEM</span></div><strong id="lockSystemState" class="lock-status-value on">فعال</strong><span>وضعیت کلی سیستم</span></div></div><div class="content-lock-notice"><span>i</span><div><b>اجرای واقعی از Bot Core</b><small>قوانین این صفحه در PostgreSQL ذخیره می‌شوند و Bot Core آن‌ها را هنگام دریافت پیام از Telegram اعمال می‌کند. برای کنترل همه پیام‌های گروه، دسترسی‌های مدیریتی و دریافت Updateها باید در Telegram به‌درستی تنظیم شده باشند.</small></div><em>LIVE POLICY</em></div><div id="contentLockEmptyGroup" class="panel-card content-lock-empty" style="display:none"><span class="lock-empty-icon">◇</span><b>هنوز گروهی در هسته ربات ثبت نشده است.</b><small>شناسه گروه را وارد کنید یا اجازه دهید ربات با اولین پیام گروه آن را ثبت کند.</small></div><div class="content-lock-shell"><nav class="content-lock-tabs">'+Object.entries(sections).map(([k,v])=>'<button class="content-lock-tab '+(state.tab===k?"active":"")+'" data-lock-tab="'+k+'"><span>'+v.icon+'</span><div><b>'+v.label+'</b><small>'+v.desc+'</small></div></button>').join("")+'</nav><main id="contentLockWorkspace" class="content-lock-workspace"></main></div>';}
  shell("سیستم قفل و کنترل محتوا","GROUP MANAGEMENT · CAPABILITY 13 / 60",shellBody());
  const workspace=document.getElementById("contentLockWorkspace");
  document.querySelectorAll("[data-lock-tab]").forEach(b=>b.onclick=()=>{state.tab=b.dataset.lockTab;renderTab();});
  document.getElementById("applyContentLockGroup").onclick=()=>selectGroup(document.getElementById("contentLockGroupId").value);
  document.getElementById("contentLockGroupSelect").onchange=e=>selectGroup(e.target.value);
  document.getElementById("contentLockEnabled").onchange=async e=>{if(!state.groupId){e.target.checked=false;toast("ابتدا گروه هدف را انتخاب کنید.","error");return;}try{await api("/api/content-locks/settings",{method:"PUT",body:JSON.stringify({group_id:state.groupId,enabled:e.target.checked,actor_id:actorId()})});state.settings.enabled=e.target.checked;toast(e.target.checked?"سیستم قفل محتوا فعال شد.":"سیستم قفل محتوا خاموش شد.");renderStats();}catch(err){e.target.checked=!e.target.checked;toast(err.message,"error");}};
  async function renderLinks(){const rows=["links_all","links_telegram","links_external","links_invites"].map(getRule).filter(Boolean);workspace.innerHTML='<div class="lock-section-head"><div><span class="eyebrow">LINK SECURITY</span><h2>لینک و تبلیغات</h2><p>هر خانواده لینک را مستقل قفل کنید و رفتار بعد از تشخیص را تعیین کنید.</p></div><span class="module-badge">'+rows.filter(x=>x.enabled).length+' قفل فعال</span></div><div class="lock-grid-2">'+rows.map(r=>ruleCard(r,'<label class="inline-field">اقدام<select data-lock-action="'+r.rule_key+'">'+actionOptions(r.config.action)+'</select></label>')).join("")+'</div><div class="lock-dual"><section class="panel-card lock-panel"><div class="lock-panel-head"><div><span class="eyebrow">LINK BEHAVIOR</span><h3>رفتار خودکار لینک</h3><small>این دو گزینه رفتار عمومی لینک‌های غیرمجاز را کنترل می‌کنند.</small></div></div>'+["links_auto_delete","links_notify"].map(k=>{const r=getRule(k);return r?ruleCard(r,""):"";}).join("")+'<div class="lock-tip">دامنه سفیدشده حتی در صورت فعال بودن قفل لینک، مجاز خواهد بود.</div></section><section class="panel-card lock-panel"><div class="lock-panel-head"><div><span class="eyebrow">DOMAIN WHITELIST</span><h3>لیست سفید دامنه‌ها</h3><small>فقط دامنه‌های مورداعتماد را اضافه کنید.</small></div></div><div class="lock-add-row"><input id="lockDomainInput" placeholder="example.com"><button class="primary" id="addLockDomain">افزودن دامنه</button></div><div class="lock-chip-list">'+(state.domains.length?state.domains.map(d=>'<span>'+escLock(d.domain)+'<button data-domain-delete="'+d.id+'">×</button></span>').join(""):'<div class="lock-empty-mini">هنوز دامنه‌ای مجاز نشده است.</div>')+'</div></section></div>';
  document.querySelectorAll("[data-lock-toggle]").forEach(i=>i.onchange=()=>toggleRule(i));document.querySelectorAll("[data-lock-action]").forEach(s=>s.onchange=()=>saveConfigRow(s.dataset.lockAction,{action:s.value}));
  document.getElementById("addLockDomain").onclick=async()=>{const v=document.getElementById("lockDomainInput").value.trim();if(!v)return;try{await api("/api/content-locks/domains",{method:"POST",body:JSON.stringify({group_id:state.groupId,domain:v,actor_id:actorId()})});toast("دامنه به لیست سفید اضافه شد.");state.domains=(await api("/api/content-locks/domains?group_id="+encodeURIComponent(state.groupId))).domains||[];renderLinks();}catch(e){toast(e.message,"error");}};
  document.querySelectorAll("[data-domain-delete]").forEach(b=>b.onclick=async()=>{await api("/api/content-locks/domains/"+b.dataset.domainDelete,{method:"DELETE"});state.domains=state.domains.filter(x=>String(x.id)!==b.dataset.domainDelete);toast("دامنه حذف شد.");renderLinks();});
  }
  async function renderMedia(){const data=[["photo","عکس"],["video","ویدیو"],["audio","موزیک / Audio"],["animation","GIF / Animation"],["sticker","استیکر"],["voice","ویس"],["video_note","ویدیو نوت"]];workspace.innerHTML='<div class="lock-section-head"><div><span class="eyebrow">MEDIA CONTROL</span><h2>رسانه</h2><p>برای هر نوع رسانه، قفل، سقف حجم، نرخ ارسال و اقدام خودکار را جداگانه تنظیم کنید.</p></div><span class="module-badge">۷ نوع رسانه</span></div><div class="lock-media-grid">'+data.map(x=>{const k="media_"+x[0],r=getRule(k);return'<section class="panel-card lock-media-card"><div class="lock-media-head"><span class="lock-media-icon">'+({photo:"▧",video:"▶",audio:"♫",animation:"∞",sticker:"✦",voice:"◉",video_note:"●"}[x[0]])+'</span><div><b>'+x[1]+'</b><small>'+k+'</small></div><label class="lock-switch"><input type="checkbox" data-lock-toggle="'+k+'" '+(r?.enabled?"checked":"")+'><span></span></label></div><div class="lock-media-fields"><label>حداکثر حجم<input type="number" data-media-field="'+k+'-max" value="'+escLock(r?.config?.max_mb??50)+'" min="0" max="4096"><em>MB · ۰ = بدون سقف</em></label><label>حداکثر در دقیقه<input type="number" data-media-field="'+k+'-rate" value="'+escLock(r?.config?.max_per_minute??0)+'" min="0" max="1000"><em>تعداد · ۰ = بدون محدودیت</em></label><label class="full">اقدام بعد از تشخیص<select data-media-field="'+k+'-action">'+actionOptions(r?.config?.action)+'</select></label></div></section>';}).join("")+'</div><div class="lock-bottom-note"><b>نکته اجرایی</b><span>سقف حجم فقط وقتی قابل ارزیابی است که Telegram در Update، اندازه فایل را همراه پیام در اختیار Bot قرار دهد؛ در سایر موارد قفل نوع محتوا همچنان قابل اعمال است.</span></div>';
  document.querySelectorAll("[data-lock-toggle]").forEach(i=>i.onchange=()=>toggleRule(i));document.querySelectorAll("[data-media-field]").forEach(el=>el.onchange=async()=>{const [k,field]=el.dataset.mediaField.split("-"),r=getRule(k),patch={...(r?.config||{})};patch[field==="max"?"max_mb":field==="rate"?"max_per_minute":"action"]=field==="action"?el.value:Number(el.value);await saveConfigRow(k,patch);});}
  async function renderForwarding(){const rows=["forward_all","forward_groups","forward_channels","forward_private"].map(getRule).filter(Boolean);workspace.innerHTML='<div class="lock-section-head"><div><span class="eyebrow">SHARING CONTROL</span><h2>فوروارد و اشتراک‌گذاری</h2><p>منبع فوروارد را مشخص کنید و منابع مجاز را از بخش استثناها مدیریت کنید.</p></div><span class="module-badge">FORWARD ORIGIN</span></div><div class="lock-grid-2">'+rows.map(r=>ruleCard(r,'<label class="inline-field">اقدام<select data-lock-action="'+r.rule_key+'">'+actionOptions(r.config.action)+'</select></label>')).join("")+'</div><section class="panel-card lock-panel"><div class="lock-panel-head"><div><span class="eyebrow">FORWARD POLICY</span><h3>رفتار اشتراک‌گذاری</h3><small>قفل و اعلان مستقل را از اینجا کنترل کنید.</small></div></div>'+["forward_auto_delete","forward_notify"].map(k=>ruleCard(getRule(k)||{rule_key:k,title:k,description:"",enabled:false,config:{}})).join("")+'<div class="lock-share-note">اشتراک‌گذاری‌های قابل تشخیص Telegram با <code>forward_origin</code> کنترل می‌شوند؛ محتوای محافظت‌شده‌ای که اصلاً Update قابل تشخیص تولید نکند، از داخل Bot قابل حذف نیست.</div></section>';
  document.querySelectorAll("[data-lock-toggle]").forEach(i=>i.onchange=()=>toggleRule(i));document.querySelectorAll("[data-lock-action]").forEach(s=>s.onchange=()=>saveConfigRow(s.dataset.lockAction,{action:s.value}));}
  async function renderFiles(){const d=getRule("file_documents"),archive=getRule("file_archives"),exe=getRule("file_executables"),max=getRule("file_max_size");const blocked=(d?.config?.blocked_extensions||[]).join(", ");const allowed=(d?.config?.allowed_extensions||[]).join(", ");workspace.innerHTML='<div class="lock-section-head"><div><span class="eyebrow">FILE GOVERNANCE</span><h2>فایل و سند</h2><p>پسوندهای مجاز و ممنوع، حجم فایل و انواع اجرایی را کنترل کنید.</p></div><span class="module-badge">DOCUMENT POLICY</span></div><div class="lock-grid-3">'+[archive,exe,d].filter(Boolean).map(r=>ruleCard(r)).join("")+'</div><div class="lock-grid-2"><section class="panel-card lock-panel"><div class="lock-panel-head"><div><span class="eyebrow">SIZE POLICY</span><h3>سقف حجم فایل</h3></div></div><div class="lock-inline-fields"><label class="lock-field">حداکثر حجم<input id="fileMaxSize" type="number" min="0" max="4096" value="'+escLock(max?.config?.max_mb??50)+'"><em>MB · ۰ = بدون سقف</em></label><label class="inline-field">اقدام<select id="fileMaxAction">'+actionOptions(max?.config?.action)+'</select></label></div>'+ruleCard(getRule("file_auto_delete")||{rule_key:"file_auto_delete",title:"حذف خودکار فایل غیرمجاز",description:"",enabled:false,config:{}})+'</section><section class="panel-card lock-panel"><div class="lock-panel-head"><div><span class="eyebrow">EXTENSION POLICY</span><h3>پسوندها</h3><small>لیست‌ها را با کاما جدا کنید؛ مثال: exe, apk, bat</small></div></div><label class="lock-textarea-label">پسوندهای ممنوع<textarea id="blockedExtensions">'+escLock(blocked)+'</textarea></label><label class="lock-textarea-label">پسوندهای مجاز<textarea id="allowedExtensions">'+escLock(allowed)+'</textarea></label><button class="primary" id="saveExtensions">ذخیره سیاست پسوند</button></section></div>';
  document.querySelectorAll("[data-lock-toggle]").forEach(i=>i.onchange=()=>toggleRule(i));document.getElementById("fileMaxSize").onchange=()=>saveConfigRow("file_max_size",{max_mb:Number(document.getElementById("fileMaxSize").value)});document.getElementById("fileMaxAction").onchange=()=>saveConfigRow("file_max_size",{action:document.getElementById("fileMaxAction").value});document.getElementById("saveExtensions").onclick=()=>saveConfigRow("file_documents",{blocked_extensions:document.getElementById("blockedExtensions").value.split(",").map(x=>x.trim().toLowerCase().replace(/^\\./,"")).filter(Boolean).slice(0,100),allowed_extensions:document.getElementById("allowedExtensions").value.split(",").map(x=>x.trim().toLowerCase().replace(/^\\./,"")).filter(Boolean).slice(0,100)});}
  async function renderMessages(){const specs=[["message_min_length","حداقل طول پیام","min_chars","کاراکتر"],["message_max_length","حداکثر طول پیام","max_chars","کاراکتر"],["message_rate_limit","سقف پیام در بازه","count","پیام / پنجره"]];workspace.innerHTML='<div class="lock-section-head"><div><span class="eyebrow">MESSAGE GOVERNANCE</span><h2>پیام</h2><p>محدودیت طول، نرخ ارسال و سیاست‌های پایه پیام را یکجا کنترل کنید.</p></div></div><div class="lock-grid-3">'+specs.map(s=>{const r=getRule(s[0]);return'<section class="panel-card lock-policy-card"><div class="lock-policy-head"><label class="lock-switch"><input type="checkbox" data-lock-toggle="'+s[0]+'" '+(r?.enabled?"checked":"")+'><span></span></label><div><b>'+s[1]+'</b><small>'+r?.rule_key+'</small></div></div><label class="lock-field">'+s[3]+'<input type="number" data-message-config="'+s[0]+'" value="'+escLock(r?.config?.[s[2]]??(s[0]==="message_max_length"?4000:s[0]==="message_rate_limit"?10:2))+'" min="1" max="20000"></label><label class="inline-field">اقدام<select data-message-action="'+s[0]+'">'+actionOptions(r?.config?.action)+'</select></label></section>';}).join("")+'</div><section class="panel-card lock-panel"><div class="lock-panel-head"><div><span class="eyebrow">FLOW CONTROL</span><h3>رفتار محدودکننده</h3><small>برای نرخ پیام، پنجره زمانی را دقیق تعیین کنید.</small></div></div><div class="lock-grid-2">'+numberField("message_rate_limit","پنجره زمانی",cfg("message_rate_limit").window_seconds??60,1,3600,"ثانیه")+'<div class="lock-explain">وقتی شمارش پیام یک کاربر از سقف عبور کند، اقدام انتخاب‌شده روی پیام اضافی اجرا می‌شود.</div></div></section>';
  document.querySelectorAll("[data-lock-toggle]").forEach(i=>i.onchange=()=>toggleRule(i));document.querySelectorAll("[data-message-config]").forEach(el=>el.onchange=()=>{const key=el.dataset.messageConfig;const field=key==="message_min_length"?"min_chars":key==="message_max_length"?"max_chars":"count";return saveConfigRow(key,{[field]:Number(el.value)})});document.querySelectorAll("[data-message-action]").forEach(el=>el.onchange=()=>saveConfigRow(el.dataset.messageAction,{action:el.value}));const rateWindow=document.querySelector('[data-lock-field="message_rate_limit"]');if(rateWindow)rateWindow.onchange=()=>saveConfigRow("message_rate_limit",{window_seconds:Number(rateWindow.value)});}
  async function renderInteractions(){const rows=["reply_lock","edit_lock","hashtag_limit","mention_limit","web_preview_lock"].map(getRule).filter(Boolean);workspace.innerHTML='<div class="lock-section-head"><div><span class="eyebrow">INTERACTION CONTROL</span><h2>تعامل، ریپلای و ویرایش</h2><p>قفل ریپلای، ویرایش متن، هشتگ/منشن انبوه و پیش‌نمایش لینک را مستقل تنظیم کنید.</p></div></div><div class="lock-grid-2">'+rows.map(r=>ruleCard(r,'<label class="inline-field">اقدام<select data-lock-action="'+r.rule_key+'">'+actionOptions(r.config.action)+'</select></label>')).join("")+'</div><div class="lock-grid-2"><section class="panel-card lock-panel"><div class="lock-panel-head"><div><span class="eyebrow">COUNT LIMITS</span><h3>سقف هشتگ و منشن</h3></div></div><div class="lock-inline-fields"><label class="lock-field">حداکثر هشتگ<input id="maxHashtags" type="number" min="1" value="'+escLock(cfg("hashtag_limit").max_hashtags??5)+'"></label><label class="lock-field">حداکثر منشن<input id="maxMentions" type="number" min="1" value="'+escLock(cfg("mention_limit").max_mentions??5)+'"></label></div><button class="primary" id="saveInteractionCounts">ذخیره سقف‌ها</button></section><section class="panel-card lock-panel"><div class="lock-panel-head"><div><span class="eyebrow">EDIT POLICY</span><h3>ویرایش و اشتراک متن</h3></div></div><div class="lock-share-note">قفل «ویرایش متن» روی <code>edited_message</code> اعمال می‌شود. قفل اشتراک‌گذاری قابل تشخیص در Telegram از بخش «فوروارد و اشتراک‌گذاری» کنترل می‌شود.</div></section></div>';
  document.querySelectorAll("[data-lock-toggle]").forEach(i=>i.onchange=()=>toggleRule(i));document.querySelectorAll("[data-lock-action]").forEach(s=>s.onchange=()=>saveConfigRow(s.dataset.lockAction,{action:s.value}));document.getElementById("saveInteractionCounts").onclick=async()=>{await saveConfigRow("hashtag_limit",{max_hashtags:Number(document.getElementById("maxHashtags").value)});await saveConfigRow("mention_limit",{max_mentions:Number(document.getElementById("maxMentions").value)});};}
  async function renderAntiAttack(){const data=[["attack_flood","ضد فلود سریع"],["attack_duplicate","ضد پیام تکراری"],["attack_caps","کنترل CAPS"],["attack_link_burst","ضد هجوم لینک"],["attack_media_burst","ضد هجوم رسانه"]];workspace.innerHTML='<div class="lock-section-head"><div><span class="eyebrow">ANTI-ATTACK ENGINE</span><h2>ضد اتک</h2><p>قوانین ضد فلود، تکرار، Burst و متن فشرده را برای هر گروه تنظیم کنید.</p></div><span class="module-badge">'+data.filter(x=>isOn(x[0])).length+' موتور فعال</span></div><div class="lock-attack-grid">'+data.map(x=>{const r=getRule(x[0]);const c=r?.config||{};return'<section class="panel-card lock-attack-card"><div class="lock-policy-head"><label class="lock-switch"><input type="checkbox" data-lock-toggle="'+x[0]+'" '+(r?.enabled?"checked":"")+'><span></span></label><div><b>'+x[1]+'</b><small>'+x[0]+'</small></div></div><div class="lock-attack-fields">'+(x[0]==="attack_caps"?'<label>درصد CAPS<input data-attack-field="'+x[0]+'-percent" type="number" min="1" max="100" value="'+escLock(c.percent??90)+'"><em>%</em></label><label>حداقل حروف<input data-attack-field="'+x[0]+'-min_letters" type="number" min="1" value="'+escLock(c.min_letters??20)+'"></label>':'<label>تعداد<input data-attack-field="'+x[0]+'-count" type="number" min="1" value="'+escLock(c.count??(x[0]==="attack_flood"?8:5))+'"></label><label>پنجره<input data-attack-field="'+x[0]+'-window_seconds" type="number" min="1" value="'+escLock(c.window_seconds??(x[0]==="attack_flood"?5:15))+'"><em>ثانیه</em></label>')+'<label class="full">اقدام<select data-attack-field="'+x[0]+'-action">'+actionOptions(c.action)+'</select></label></div></section>';}).join("")+'</div>';
  document.querySelectorAll("[data-lock-toggle]").forEach(i=>i.onchange=()=>toggleRule(i));document.querySelectorAll("[data-attack-field]").forEach(el=>el.onchange=async()=>{const [k,f]=el.dataset.attackField.split("-");await saveConfigRow(k,{[f]:f==="action"?el.value:Number(el.value)});});}
  async function renderAdvanced(){const data=[["contact_lock","Contact"],["location_lock","Location / Venue"],["poll_lock","Poll"],["dice_lock","Dice"],["game_lock","Game"],["web_app_lock","Web App Data"]];workspace.innerHTML='<div class="lock-section-head"><div><span class="eyebrow">ADVANCED PAYLOADS</span><h2>محتوای پیشرفته</h2><p>پیام‌های غیرمتنی و تعامل‌های ویژه Telegram را مستقل قفل کنید.</p></div></div><div class="lock-grid-3">'+data.map(x=>{const r=getRule(x[0]);return ruleCard(r||{rule_key:x[0],title:x[1],description:"",enabled:false,config:{}},'<label class="inline-field">اقدام<select data-lock-action="'+x[0]+'">'+actionOptions(r?.config?.action)+'</select></label>');}).join("")+'</div><div class="lock-bottom-note"><b>کنترل کامل Update</b><span>قفل‌های این بخش مستقیماً روی فیلدهای محتوایی پیام Telegram اعمال می‌شوند؛ بنابراین ربات فقط مواردی را مسدود می‌کند که در Update دریافتی قابل تشخیص باشند.</span></div>';document.querySelectorAll("[data-lock-toggle]").forEach(i=>i.onchange=()=>toggleRule(i));document.querySelectorAll("[data-lock-action]").forEach(s=>s.onchange=()=>saveConfigRow(s.dataset.lockAction,{action:s.value}));}
  function renderExceptions(){workspace.innerHTML='<div class="lock-section-head"><div><span class="eyebrow">EXCEPTION ENGINE</span><h2>استثناها و لیست سفید</h2><p>کاربر، نقش یا منبع فوروارد را از بخشی از قوانین معاف کنید.</p></div><button class="primary" id="addLockException">+ افزودن استثنا</button></div><section class="panel-card lock-panel"><div class="lock-table-wrap"><table class="lock-table"><thead><tr><th>#</th><th>نوع</th><th>هدف</th><th>محدوده</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>'+((state.exceptions.length?state.exceptions.map((x,i)=>'<tr><td>'+String(i+1)+'</td><td>'+({"user":"کاربر","role":"نقش","forward_source":"منبع فوروارد"}[x.exception_type]||x.exception_type)+'</td><td><b>'+escLock(x.target_label||x.target_id)+'</b><small>'+escLock(x.target_id)+'</small></td><td>'+escLock(Array.isArray(x.scope)?x.scope.join(" · "):"همه")+'</td><td><span class="lock-badge on">فعال</span></td><td><button class="ghost small" data-exception-edit="'+x.id+'">ویرایش</button><button class="ghost small danger" data-exception-delete="'+x.id+'">حذف</button></td></tr>').join(""):'<tr><td colspan="6"><div class="lock-empty-mini">استثنایی تعریف نشده است؛ در این حالت فقط معافیت مدیران طبق تنظیمات مرکزی اعمال می‌شود.</div></td></tr>'))+'</tbody></table></div></section>';
  document.getElementById("addLockException").onclick=()=>openExceptionModal();document.querySelectorAll("[data-exception-edit]").forEach(b=>b.onclick=()=>openExceptionModal(state.exceptions.find(x=>String(x.id)===b.dataset.exceptionEdit)));document.querySelectorAll("[data-exception-delete]").forEach(b=>b.onclick=async()=>{if(!confirm("این استثنا حذف شود؟"))return;await api("/api/content-locks/exceptions/"+b.dataset.exceptionDelete,{method:"DELETE"});toast("استثنا حذف شد.");state.exceptions=(await api("/api/content-locks/exceptions?group_id="+encodeURIComponent(state.groupId))).exceptions||[];renderExceptions();renderStats({...(await api("/api/content-locks/overview?group_id="+encodeURIComponent(state.groupId))).stats});});}
  function openExceptionModal(item){const scopes=Object.entries(sections).filter(x=>!["exceptions","logs","tester"].includes(x[0]));const types=[["user","کاربر خاص"],["role","نقش خاص"],["forward_source","چت / منبع فوروارد"]];const w=document.createElement("div");w.className="modal-backdrop";w.innerHTML='<div class="modal content-lock-modal"><div class="modal-head"><div><span class="eyebrow">EXCEPTION ENGINE · CAPABILITY 13</span><h2>'+(item?"ویرایش استثنا":"افزودن استثنا")+'</h2></div><button class="modal-close">×</button></div><form id="lockExceptionForm" class="form-grid"><label>نوع استثنا<select name="exception_type">'+types.map(x=>'<option value="'+x[0]+'" '+(item?.exception_type===x[0]?"selected":"")+'>'+x[1]+'</option>').join("")+'</select></label><label>شناسه هدف<input name="target_id" required value="'+escLock(item?.target_id||"")+'" placeholder="Telegram ID یا Chat ID"></label><label>نام نمایشی<input name="target_label" value="'+escLock(item?.target_label||"")+'" placeholder="مثلاً @example"></label><div class="full lock-scope-box"><b>محدوده معافیت</b><small>فقط بخش‌های انتخاب‌شده برای این هدف نادیده گرفته می‌شوند.</small><div class="lock-scope-grid"><label><input type="checkbox" name="scope" value="all" '+((item?.scope||["all"]).includes("all")?"checked":"")+'> همه بخش‌ها</label>'+scopes.map(x=>'<label><input type="checkbox" name="scope" value="'+x[0]+'" '+((item?.scope||[]).includes(x[0])?"checked":"")+'>'+x[1].label+'</label>').join("")+'</div></div><div class="form-actions"><button type="button" class="ghost" id="lockExcCancel">انصراف</button><button class="primary" type="submit">ذخیره استثنا</button></div></form></div>';document.body.appendChild(w);const close=()=>w.remove();w.querySelector(".modal-close").onclick=close;w.querySelector("#lockExcCancel").onclick=close;w.querySelector("#lockExceptionForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const scope=f.getAll("scope");try{await api(item?"/api/content-locks/exceptions/"+item.id:"/api/content-locks/exceptions",{method:item?"PUT":"POST",body:JSON.stringify({group_id:state.groupId,exception_type:f.get("exception_type"),target_id:f.get("target_id"),target_label:f.get("target_label"),scope:scope.length?scope:["all"],actor_id:actorId()})});close();toast("استثنا ذخیره شد.");state.exceptions=(await api("/api/content-locks/exceptions?group_id="+encodeURIComponent(state.groupId))).exceptions||[];renderExceptions();}catch(err){toast(err.message,"error");}};}
  async function renderLogs(){const p=new URLSearchParams({group_id:state.groupId,page:String(state.logsPage),limit:"20"});if(state.logQ)p.set("q",state.logQ);if(state.logType)p.set("type",state.logType);if(state.logFrom)p.set("from",state.logFrom);if(state.logTo)p.set("to",state.logTo);workspace.innerHTML='<div class="lock-section-head"><div><span class="eyebrow">AUDIT TRAIL</span><h2>لاگ‌های قفل محتوا</h2><p>تمام حذف‌ها، اخطارها و جریمه‌های ناشی از این قابلیت را مشاهده کنید.</p></div><div class="lock-log-head-actions"><button class="ghost" id="exportLockLogs">خروجی CSV</button></div></div><section class="panel-card lock-panel"><div class="lock-log-filters"><div class="searchbox">⌕ <input id="lockLogSearch" placeholder="جستجوی کاربر، Username یا شناسه..." value="'+escLock(state.logQ)+'"></div><select id="lockLogType"><option value="">همه نوع محتوا</option>'+["link","photo","video","audio","animation","sticker","voice","video_note","forward","file","text","reply","edited_message","attack","contact","location","poll","dice","game","web_app"].map(x=>'<option value="'+x+'" '+(state.logType===x?"selected":"")+'>'+x+'</option>').join("")+'</select><input id="lockLogFrom" type="date" value="'+escLock(state.logFrom)+'"><input id="lockLogTo" type="date" value="'+escLock(state.logTo)+'"><button class="primary" id="applyLockLogFilters">اعمال فیلتر</button></div><div id="lockLogsTable" class="lock-table-wrap"><div class="loading-state">در حال دریافت لاگ...</div></div></section>';
  const d=await api("/api/content-locks/logs?"+p.toString());const rows=d.logs||[];document.getElementById("lockLogsTable").innerHTML='<table class="lock-table"><thead><tr><th>تاریخ و ساعت</th><th>نوع محتوا</th><th>کاربر متخلف</th><th>قانون</th><th>اقدام</th><th>ادمین مسئول</th></tr></thead><tbody>'+(rows.length?rows.map(x=>'<tr><td>'+escLock(faDate(x.created_at))+'</td><td><span class="lock-type">'+escLock(x.content_type)+'</span></td><td><b>'+escLock(x.first_name||"بدون نام")+'</b><small>'+escLock(x.username?"@"+x.username:x.user_id||"—")+'</small></td><td>'+escLock(x.rule_key)+'</td><td>'+escLock({"delete":"حذف","delete_notify":"حذف + اخطار","delete_mute":"حذف + سکوت","delete_ban":"حذف + اخراج موقت","delete_failed":"خطای حذف"}[x.action]||x.action)+'</td><td>'+escLock(x.admin_id||"سیستم")+'</td></tr>').join(""):'<tr><td colspan="6"><div class="lock-empty-mini">هنوز رویداد مسدودی ثبت نشده است.</div></td></tr>')+'</tbody></table><div class="lock-pagination"><span>تعداد نتایج: '+d.total+'</span><div><button class="ghost" id="lockPrev" '+(state.logsPage<=1?"disabled":"")+'>قبلی</button><b>صفحه '+state.logsPage+'</b><button class="ghost" id="lockNext" '+(state.logsPage*20>=d.total?"disabled":"")+'>بعدی</button></div></div>';
  document.getElementById("applyLockLogFilters").onclick=()=>{state.logQ=document.getElementById("lockLogSearch").value.trim();state.logType=document.getElementById("lockLogType").value;state.logFrom=document.getElementById("lockLogFrom").value;state.logTo=document.getElementById("lockLogTo").value;state.logsPage=1;renderLogs();};document.getElementById("lockPrev").onclick=()=>{if(state.logsPage>1){state.logsPage--;renderLogs();}};document.getElementById("lockNext").onclick=()=>{if(state.logsPage*20<d.total){state.logsPage++;renderLogs();}};document.getElementById("exportLockLogs").onclick=()=>{window.open("/api/content-locks/export?group_id="+encodeURIComponent(state.groupId),"_blank");};
  }
  async function renderTester(){workspace.innerHTML='<div class="lock-section-head"><div><span class="eyebrow">LIVE POLICY TESTER</span><h2>تستر قوانین</h2><p>یک پیام نمونه وارد کنید تا قوانین فعال و Matchهای احتمالی را پیش از اجرا ببینید.</p></div><span class="module-badge">SAFE TEST</span></div><section class="panel-card lock-tester"><div class="lock-tester-fields"><label>نوع محتوا<select id="lockTestType">'+["text","photo","video","audio","animation","sticker","voice","video_note","forward","file"].map(x=>'<option value="'+x+'">'+x+'</option>').join("")+'</select></label><label class="full">متن یا کپشن نمونه<textarea id="lockTestText" placeholder="https://example.com یا یک پیام نمونه..."></textarea></label></div><div class="form-actions"><button class="primary" id="runLockTest">اجرای تست</button></div><div id="lockTestResult" class="lock-test-result"><div class="lock-empty-mini">هنوز تست اجرا نشده است.</div></div></section>';
  document.getElementById("runLockTest").onclick=async()=>{try{const d=await api("/api/content-locks/test",{method:"POST",body:JSON.stringify({group_id:state.groupId,text:document.getElementById("lockTestText").value,content_type:document.getElementById("lockTestType").value})});document.getElementById("lockTestResult").innerHTML=d.matches?.length?'<div class="lock-match-head">قوانین منطبق</div>'+d.matches.map(x=>'<div class="lock-match"><span>✓</span><div><b>'+escLock(x.title)+'</b><small>'+escLock(x.rule_key)+' · '+escLock(x.section)+'</small></div></div>').join(""):'<div class="lock-test-pass">هیچ قانون فعالی روی نمونه منطبق نشد.</div>';}catch(e){toast(e.message,"error");}};
  }
  async function renderTab(){if(!state.groupId){workspace.innerHTML='<div class="lock-empty large"><span class="lock-empty-icon">◇</span><b>گروه هدف انتخاب نشده است.</b><small>ابتدا یک گروه یا شناسه گروه وارد کنید تا سیاست‌ها و قوانین آن بارگذاری شوند.</small></div>';return;}try{if(state.tab==="links")return renderLinks();if(state.tab==="media")return renderMedia();if(state.tab==="forwarding")return renderForwarding();if(state.tab==="files")return renderFiles();if(state.tab==="messages")return renderMessages();if(state.tab==="interactions")return renderInteractions();if(state.tab==="anti_attack")return renderAntiAttack();if(state.tab==="advanced")return renderAdvanced();if(state.tab==="exceptions")return renderExceptions();if(state.tab==="logs")return renderLogs();if(state.tab==="tester")return renderTester();}catch(e){workspace.innerHTML='<div class="lock-empty large error-state">خطا در نمایش بخش: '+escLock(e.message)+'</div>';}}
  await loadGroups();if(state.groupId){await loadAll();}else{renderStats(null);renderTab();}
}
