const { pool, query } = require("./database");

const PENALTIES = new Set(["mute","restrict","temp_ban","permanent_ban"]);
const DURATION_UNITS = new Set(["hours","days"]);

function send(res,status,body){res.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"});res.end(body);}
function validId(value){const s=String(value??"").trim();return /^-?[0-9]+$/.test(s)&&s!=="0"?s:null;}
function intValue(value,fallback,min,max){const n=Number(value);if(!Number.isFinite(n))return fallback;return Math.min(Math.max(Math.trunc(n),min),max);}
function cleanText(value,max=1000){return String(value??"").trim().slice(0,max);}
function durationValue(value,fallback=null){const n=Number(value);if(!Number.isFinite(n)||n<=0)return fallback;return Math.min(Math.trunc(n),3650);}
async function readBody(req){return new Promise((resolve,reject)=>{let data="";req.on("data",chunk=>{data+=chunk;if(data.length>1024*1024){reject(new Error("Request body too large"));req.destroy();}});req.on("end",()=>{try{resolve(data?JSON.parse(data):{});}catch{reject(new Error("Invalid JSON"));}});req.on("error",reject);});}
async function audit(action,actorId,target,beforeData,afterData){try{await query("INSERT INTO audit_logs (actor_id,action,target,before_data,after_data,source) VALUES ($1,$2,$3,$4::jsonb,$5::jsonb,'panel')",[actorId||null,action,target||null,JSON.stringify(beforeData||null),JSON.stringify(afterData||null)]);}catch(error){console.error("[warnings] audit failed:",error.message);}}
async function ensureWarningsSchema(){
  await query("CREATE TABLE IF NOT EXISTS bot_groups (id BIGINT PRIMARY KEY,title TEXT,username TEXT,type TEXT,is_active BOOLEAN NOT NULL DEFAULT TRUE,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())");
  await query("CREATE TABLE IF NOT EXISTS warning_system_settings (group_id BIGINT PRIMARY KEY,enabled BOOLEAN NOT NULL DEFAULT TRUE,auto_expire_enabled BOOLEAN NOT NULL DEFAULT FALSE,expire_after_days INTEGER NOT NULL DEFAULT 30,notify_private BOOLEAN NOT NULL DEFAULT FALSE,exempt_admins BOOLEAN NOT NULL DEFAULT TRUE,permanent_threshold INTEGER NOT NULL DEFAULT 5,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())");
  await query("CREATE TABLE IF NOT EXISTS warning_levels (id BIGSERIAL PRIMARY KEY,group_id BIGINT NOT NULL,level_no INTEGER NOT NULL,name TEXT NOT NULL,warning_count_required INTEGER NOT NULL,penalty_type TEXT NOT NULL,duration_value INTEGER,duration_unit TEXT,message_fa TEXT NOT NULL DEFAULT '',enabled BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(group_id,level_no))");
  await query("CREATE TABLE IF NOT EXISTS warning_cases (id BIGSERIAL PRIMARY KEY,group_id BIGINT NOT NULL,user_id BIGINT NOT NULL,first_name TEXT,username TEXT,warning_count INTEGER NOT NULL DEFAULT 0,current_level INTEGER NOT NULL DEFAULT 0,last_violation_type TEXT,last_warning_at TIMESTAMPTZ,status TEXT NOT NULL DEFAULT 'cleared',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(group_id,user_id))");
  await query("CREATE TABLE IF NOT EXISTS warning_events (id BIGSERIAL PRIMARY KEY,group_id BIGINT NOT NULL,user_id BIGINT NOT NULL,first_name TEXT,username TEXT,action_type TEXT NOT NULL,violation_type TEXT,custom_violation TEXT,level_no INTEGER,message_fa TEXT,penalty_type TEXT,duration_value INTEGER,duration_unit TEXT,admin_id TEXT,admin_name TEXT,status TEXT NOT NULL DEFAULT 'active',result TEXT NOT NULL DEFAULT 'queued',expires_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())");
  await query("CREATE TABLE IF NOT EXISTS warning_penalties (id BIGSERIAL PRIMARY KEY,group_id BIGINT NOT NULL,user_id BIGINT NOT NULL,event_id BIGINT REFERENCES warning_events(id) ON DELETE SET NULL,penalty_type TEXT NOT NULL,duration_value INTEGER,duration_unit TEXT,reason TEXT,admin_id TEXT,admin_name TEXT,status TEXT NOT NULL DEFAULT 'pending',expires_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),applied_at TIMESTAMPTZ)");
  await query("CREATE TABLE IF NOT EXISTS warning_action_queue (id BIGSERIAL PRIMARY KEY,group_id BIGINT NOT NULL,user_id BIGINT NOT NULL,event_id BIGINT REFERENCES warning_events(id) ON DELETE CASCADE,penalty_id BIGINT REFERENCES warning_penalties(id) ON DELETE CASCADE,action_type TEXT NOT NULL,message TEXT,penalty_type TEXT,duration_value INTEGER,duration_unit TEXT,status TEXT NOT NULL DEFAULT 'pending',attempts INTEGER NOT NULL DEFAULT 0,available_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),last_error TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),processed_at TIMESTAMPTZ)");
  await query("CREATE INDEX IF NOT EXISTS idx_warning_levels_group ON warning_levels(group_id,level_no)");
  await query("CREATE INDEX IF NOT EXISTS idx_warning_cases_group_status ON warning_cases(group_id,status)");
  await query("CREATE INDEX IF NOT EXISTS idx_warning_events_group_user ON warning_events(group_id,user_id,created_at DESC)");
  await query("CREATE INDEX IF NOT EXISTS idx_warning_queue_pending ON warning_action_queue(status,available_at,id)");
  await query("CREATE INDEX IF NOT EXISTS idx_warning_penalties_group_user ON warning_penalties(group_id,user_id,created_at DESC)");
  await query("CREATE INDEX IF NOT EXISTS idx_warning_penalties_active ON warning_penalties(group_id,status,expires_at)");
  await query("CREATE INDEX IF NOT EXISTS idx_bot_groups_active ON bot_groups(is_active,updated_at DESC)");
}
async function ensureGroup(groupId){
  await query("INSERT INTO bot_groups (id,title,username,type,is_active,updated_at) VALUES ($1,'',NULL,'supergroup',TRUE,NOW()) ON CONFLICT (id) DO NOTHING",[groupId]);
  await query("INSERT INTO warning_system_settings (group_id) VALUES ($1) ON CONFLICT (group_id) DO NOTHING",[groupId]);
  const c=await query("SELECT COUNT(*)::int AS count FROM warning_levels WHERE group_id=$1",[groupId]);
  if(Number(c.rows[0]?.count||0)===0){
    const d=[[1,"اخطار اول",1,"mute",1,"hours","اخطار اول برای این تخلف ثبت شد. لطفاً قوانین گروه را رعایت کنید."],[2,"اخطار دوم",2,"restrict",6,"hours","اخطار دوم ثبت شد. تکرار تخلف باعث تشدید جریمه خواهد شد."],[3,"اخطار نهایی",3,"temp_ban",1,"days","این اخطار نهایی است. ادامه تخلف می‌تواند منجر به اخراج شود."]];
    for(const row of d)await query("INSERT INTO warning_levels(group_id,level_no,name,warning_count_required,penalty_type,duration_value,duration_unit,message_fa) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(group_id,level_no) DO NOTHING",[groupId,...row]);
  }
}
async function settingsFor(groupId){await ensureGroup(groupId);return (await query("SELECT group_id,enabled,auto_expire_enabled,expire_after_days,notify_private,exempt_admins,permanent_threshold,updated_at FROM warning_system_settings WHERE group_id=$1",[groupId])).rows[0];}
function penaltyCheck(type,duration,unit){if(!PENALTIES.has(type))return "نوع جریمه نامعتبر است";if(type!=="permanent_ban"&&(!duration||!DURATION_UNITS.has(unit)))return "مدت جریمه برای این نوع ضروری است";return null;}
function levelPayload(body,fallback={}){const name=cleanText(body.name??fallback.name,120),required=intValue(body.warning_count_required??fallback.warning_count_required,1,1,100),penalty=String(body.penalty_type??fallback.penalty_type??"mute"),duration=durationValue(body.duration_value??fallback.duration_value,null),unit=String(body.duration_unit??fallback.duration_unit??"hours"),message=cleanText(body.message_fa??fallback.message_fa,2000),enabled=body.enabled===undefined?fallback.enabled!==false:body.enabled===true;return {name,required,penalty,duration,unit,message,enabled,error:!name?"نام سطح الزامی است":penaltyCheck(penalty,duration,unit)};}

async function warningsApi(req,res,url){
  try{
    if(req.method==="GET"&&url.pathname==="/api/warnings/groups"){const rows=(await query("SELECT id,title,username,type,is_active,updated_at FROM bot_groups WHERE is_active=TRUE ORDER BY updated_at DESC LIMIT 100")).rows;return send(res,200,JSON.stringify({groups:rows}));}
    if(req.method==="GET"&&url.pathname==="/api/warnings/overview"){const groupId=validId(url.searchParams.get("group_id"));if(!groupId)return send(res,400,JSON.stringify({error:"group_id is required"}));const settings=await settingsFor(groupId);const [a,m,p]=await Promise.all([query("SELECT COUNT(*)::int AS count FROM warning_events WHERE group_id=$1 AND action_type='warning' AND status='active'",[groupId]),query("SELECT COUNT(*)::int AS count FROM warning_cases WHERE group_id=$1 AND warning_count>0",[groupId]),query("SELECT COUNT(*)::int AS count FROM warning_penalties WHERE group_id=$1 AND created_at>=NOW()-INTERVAL '30 days'",[groupId])]);return send(res,200,JSON.stringify({settings,stats:{activeWarnings:a.rows[0].count,warningMembers:m.rows[0].count,penalties30d:p.rows[0].count}}));}
    if(req.method==="GET"&&url.pathname==="/api/warnings/settings"){const groupId=validId(url.searchParams.get("group_id"));if(!groupId)return send(res,400,JSON.stringify({error:"group_id is required"}));return send(res,200,JSON.stringify({settings:await settingsFor(groupId)}));}
    if(req.method==="PUT"&&url.pathname==="/api/warnings/settings"){const body=await readBody(req),groupId=validId(body.group_id);if(!groupId)return send(res,400,JSON.stringify({error:"group_id is required"}));const before=await settingsFor(groupId),next={enabled:body.enabled===undefined?before.enabled:body.enabled===true,auto_expire_enabled:body.auto_expire_enabled===true,expire_after_days:intValue(body.expire_after_days,before.expire_after_days,1,3650),notify_private:body.notify_private===true,exempt_admins:body.exempt_admins===undefined?before.exempt_admins:body.exempt_admins===true,permanent_threshold:intValue(body.permanent_threshold,before.permanent_threshold,1,100)};const saved=(await query("UPDATE warning_system_settings SET enabled=$1,auto_expire_enabled=$2,expire_after_days=$3,notify_private=$4,exempt_admins=$5,permanent_threshold=$6,updated_at=NOW() WHERE group_id=$7 RETURNING *",[next.enabled,next.auto_expire_enabled,next.expire_after_days,next.notify_private,next.exempt_admins,next.permanent_threshold,groupId])).rows[0];await audit("warning_settings_changed",body.actor_id,groupId,before,saved);return send(res,200,JSON.stringify({settings:saved}));}
    if(req.method==="GET"&&url.pathname==="/api/warnings/levels"){const groupId=validId(url.searchParams.get("group_id"));if(!groupId)return send(res,400,JSON.stringify({error:"group_id is required"}));await ensureGroup(groupId);return send(res,200,JSON.stringify({levels:(await query("SELECT * FROM warning_levels WHERE group_id=$1 ORDER BY level_no",[groupId])).rows}));}
    if(req.method==="POST"&&url.pathname==="/api/warnings/levels"){const body=await readBody(req),groupId=validId(body.group_id);if(!groupId)return send(res,400,JSON.stringify({error:"group_id is required"}));await ensureGroup(groupId);const count=Number((await query("SELECT COUNT(*)::int AS count FROM warning_levels WHERE group_id=$1",[groupId])).rows[0].count||0);if(count>=5)return send(res,409,JSON.stringify({error:"حداکثر ۵ سطح مجاز است"}));const p=levelPayload(body);if(p.error)return send(res,400,JSON.stringify({error:p.error}));const maxNo=Number((await query("SELECT COALESCE(MAX(level_no),0)::int AS level_no FROM warning_levels WHERE group_id=$1",[groupId])).rows[0].level_no||0),levelNo=intValue(body.level_no,maxNo+1,1,5);const dup=await query("SELECT 1 FROM warning_levels WHERE group_id=$1 AND level_no=$2",[groupId,levelNo]);if(dup.rowCount)return send(res,409,JSON.stringify({error:"این شماره سطح قبلاً استفاده شده است"}));const row=(await query("INSERT INTO warning_levels(group_id,level_no,name,warning_count_required,penalty_type,duration_value,duration_unit,message_fa,enabled) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *",[groupId,levelNo,p.name,p.required,p.penalty,p.duration,p.penalty==="permanent_ban"?null:p.unit,p.message,p.enabled])).rows[0];await audit("warning_level_created",body.actor_id,String(row.id),null,row);return send(res,201,JSON.stringify({level:row}));}
    const levelMatch=url.pathname.match(/^\/api\/warnings\/levels\/([0-9]+)$/);
    if(levelMatch&&(req.method==="PUT"||req.method==="DELETE")){const id=Number(levelMatch[1]),before=(await query("SELECT * FROM warning_levels WHERE id=$1",[id])).rows[0];if(!before)return send(res,404,JSON.stringify({error:"Level not found"}));if(req.method==="DELETE"){const count=Number((await query("SELECT COUNT(*)::int AS count FROM warning_levels WHERE group_id=$1",[before.group_id])).rows[0].count||0);if(count<=1)return send(res,400,JSON.stringify({error:"حداقل یک سطح باید باقی بماند"}));await query("DELETE FROM warning_levels WHERE id=$1",[id]);await audit("warning_level_deleted",null,String(id),before,null);return send(res,200,JSON.stringify({success:true}));}const body=await readBody(req),p=levelPayload(body,before);if(p.error)return send(res,400,JSON.stringify({error:p.error}));const levelNo=intValue(body.level_no,before.level_no,1,5),conflict=await query("SELECT 1 FROM warning_levels WHERE group_id=$1 AND level_no=$2 AND id<>$3",[before.group_id,levelNo,id]);if(conflict.rowCount)return send(res,409,JSON.stringify({error:"شماره سطح تکراری است"}));const row=(await query("UPDATE warning_levels SET level_no=$1,name=$2,warning_count_required=$3,penalty_type=$4,duration_value=$5,duration_unit=$6,message_fa=$7,enabled=$8,updated_at=NOW() WHERE id=$9 RETURNING *",[levelNo,p.name,p.required,p.penalty,p.duration,p.penalty==="permanent_ban"?null:p.unit,p.message,p.enabled,id])).rows[0];await audit("warning_level_updated",body.actor_id,String(id),before,row);return send(res,200,JSON.stringify({level:row}));}
    if(req.method==="GET"&&url.pathname==="/api/warnings/members"){const groupId=validId(url.searchParams.get("group_id"));if(!groupId)return send(res,400,JSON.stringify({error:"group_id is required"}));const q=cleanText(url.searchParams.get("q"),120).toLowerCase(),status=String(url.searchParams.get("status")||"all"),page=Math.max(Number(url.searchParams.get("page")||1),1),limit=Math.min(Math.max(Number(url.searchParams.get("limit")||10),5),50),offset=(page-1)*limit,params=[groupId],where=["c.group_id=$1"];if(q){params.push("%"+q+"%");where.push("LOWER(COALESCE(c.first_name,'')||' '||COALESCE(c.username,'')||' '||c.user_id::text) LIKE $"+params.length);}if(status==="active")where.push("c.warning_count>0");if(status==="penalized")where.push("p.status='active'");if(status==="cleared")where.push("c.warning_count=0 AND COALESCE(p.status,'')<>'active'");params.push(limit,offset);const rows=(await query("SELECT c.*,p.penalty_type,p.duration_value,p.duration_unit,p.expires_at,p.status AS penalty_status,COUNT(*) OVER()::int AS total_count FROM warning_cases c LEFT JOIN LATERAL (SELECT * FROM warning_penalties wp WHERE wp.group_id=c.group_id AND wp.user_id=c.user_id ORDER BY wp.created_at DESC LIMIT 1) p ON TRUE WHERE "+where.join(" AND ")+" ORDER BY COALESCE(c.last_warning_at,c.updated_at) DESC LIMIT $"+(params.length-1)+" OFFSET $"+params.length,params)).rows;return send(res,200,JSON.stringify({page,limit,total:Number(rows[0]?.total_count||0),members:rows.map(x=>{const y={...x};delete y.total_count;return y;})}));}
    const historyMatch=url.pathname.match(/^\/api\/warnings\/history\/(-?[0-9]+)\/([0-9]+)$/);
    if(req.method==="GET"&&historyMatch){const groupId=historyMatch[1],userId=historyMatch[2],user=(await query("SELECT * FROM warning_cases WHERE group_id=$1 AND user_id=$2 LIMIT 1",[groupId,userId])).rows[0]||null,events=(await query("SELECT id,action_type,violation_type,custom_violation,level_no,message_fa,penalty_type,duration_value,duration_unit,admin_id,admin_name,status,result,expires_at,created_at FROM warning_events WHERE group_id=$1 AND user_id=$2 ORDER BY created_at DESC LIMIT 200",[groupId,userId])).rows;return send(res,200,JSON.stringify({user,events}));}
    if(req.method==="GET"&&url.pathname==="/api/warnings/logs"){const groupId=validId(url.searchParams.get("group_id"));if(!groupId)return send(res,400,JSON.stringify({error:"group_id is required"}));return send(res,200,JSON.stringify({logs:(await query("SELECT id,action_type,violation_type,custom_violation,level_no,penalty_type,duration_value,duration_unit,admin_id,admin_name,status,result,created_at,user_id,first_name,username FROM warning_events WHERE group_id=$1 ORDER BY created_at DESC LIMIT 20",[groupId])).rows}));}
    if(req.method==="POST"&&url.pathname==="/api/warnings/issue"){const body=await readBody(req),groupId=validId(body.group_id),userId=validId(body.user_id);if(!groupId||!userId)return send(res,400,JSON.stringify({error:"group_id and user_id are required"}));const settings=await settingsFor(groupId);if(!settings.enabled)return send(res,409,JSON.stringify({error:"سیستم اخطار برای این گروه غیرفعال است"}));const violation=cleanText(body.violation_type||"other",120),custom=cleanText(body.custom_violation,500),actorId=cleanText(body.admin_id||"PANEL_OWNER",120),actorName=cleanText(body.admin_name||"مدیر پنل",120),firstName=cleanText(body.first_name||body.user_name||"",160),username=cleanText(body.username||"",160),client=await pool.connect();
      try{
        await client.query("BEGIN");
        const existing=(await client.query("SELECT * FROM warning_cases WHERE group_id=$1 AND user_id=$2 FOR UPDATE",[groupId,userId])).rows[0];
        if(!existing)await client.query("INSERT INTO warning_cases(group_id,user_id,first_name,username) VALUES($1,$2,$3,$4)",[groupId,userId,firstName,username]);else await client.query("UPDATE warning_cases SET first_name=COALESCE(NULLIF($3,''),first_name),username=COALESCE(NULLIF($4,''),username),updated_at=NOW() WHERE group_id=$1 AND user_id=$2",[groupId,userId,firstName,username]);
        const active=Number((await client.query("SELECT COUNT(*)::int AS count FROM warning_events WHERE group_id=$1 AND user_id=$2 AND action_type='warning' AND status='active'",[groupId,userId])).rows[0].count||0),nextCount=active+1,levels=(await client.query("SELECT * FROM warning_levels WHERE group_id=$1 AND enabled=TRUE ORDER BY warning_count_required DESC,level_no DESC",[groupId])).rows,selected=body.level_id?levels.find(x=>String(x.id)===String(body.level_id)):null,triggered=levels.find(x=>Number(x.warning_count_required)<=nextCount)||null,immediate=body.apply_immediate_penalty===true&&selected?selected:null,penaltyLevel=immediate||triggered;
        let penaltyType=penaltyLevel?.penalty_type||null,penaltyDuration=penaltyLevel?.duration_value||null,penaltyUnit=penaltyLevel?.duration_unit||null,penaltyLevelNo=penaltyLevel?.level_no||triggered?.level_no||null;
        if(nextCount>=Number(settings.permanent_threshold||5)){penaltyType="permanent_ban";penaltyDuration=null;penaltyUnit=null;penaltyLevelNo=penaltyLevelNo||triggered?.level_no||null;}
        const message=cleanText(body.message_fa||selected?.message_fa||triggered?.message_fa||"اخطار برای این تخلف ثبت شد. لطفاً قوانین گروه را رعایت کنید.",2000),expiresAt=settings.auto_expire_enabled?new Date(Date.now()+Number(settings.expire_after_days)*86400000):null;
        const event=(await client.query("INSERT INTO warning_events(group_id,user_id,first_name,username,action_type,violation_type,custom_violation,level_no,message_fa,penalty_type,duration_value,duration_unit,admin_id,admin_name,status,result,expires_at) VALUES($1,$2,$3,$4,'warning',$5,$6,$7,$8,$9,$10,$11,$12,$13,'active','queued',$14) RETURNING *",[groupId,userId,firstName,username,violation,custom,penaltyLevelNo,message,penaltyType,penaltyDuration,penaltyUnit,actorId,actorName,expiresAt])).rows[0];
        await client.query("INSERT INTO warning_action_queue(group_id,user_id,event_id,action_type,message,status) VALUES($1,$2,$3,'warning_notify',$4,'pending')",[groupId,userId,event.id,message]);
        let penalty=null;
        if(penaltyType){const pc=penaltyCheck(penaltyType,penaltyDuration,penaltyUnit);if(pc)throw new Error(pc);penalty=(await client.query("INSERT INTO warning_penalties(group_id,user_id,event_id,penalty_type,duration_value,duration_unit,reason,admin_id,admin_name,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'pending') RETURNING *",[groupId,userId,event.id,penaltyType,penaltyDuration,penaltyUnit,custom||violation,actorId,actorName])).rows[0];await client.query("INSERT INTO warning_action_queue(group_id,user_id,event_id,penalty_id,action_type,penalty_type,duration_value,duration_unit,status) VALUES($1,$2,$3,$4,'penalty_apply',$5,$6,$7,'pending')",[groupId,userId,event.id,penalty.id,penaltyType,penaltyDuration,penaltyUnit]);}
        await client.query("UPDATE warning_cases SET warning_count=$3,current_level=$4,last_violation_type=$5,last_warning_at=NOW(),status=$6,updated_at=NOW() WHERE group_id=$1 AND user_id=$2",[groupId,userId,nextCount,penaltyLevelNo||0,violation,penalty?"penalized":"active"]);
        await client.query("COMMIT");await audit("warning_issued",actorId,groupId,null,{user_id:userId,violation,warning_count:nextCount,penalty_type:penaltyType});
        return send(res,201,JSON.stringify({success:true,event,penalty,warning_count:nextCount,triggered_level:triggered?.level_no||null}));
      }catch(error){await client.query("ROLLBACK").catch(()=>{});throw error;}finally{client.release();}
    }
    const clearMatch=url.pathname.match(/^\/api\/warnings\/members\/(-?[0-9]+)\/([0-9]+)\/clear$/);
    if(req.method==="POST"&&clearMatch){const body=await readBody(req),groupId=clearMatch[1],userId=clearMatch[2];if(body.confirmation!=="CLEAR_WARNINGS")return send(res,400,JSON.stringify({error:"تأیید دومرحله‌ای الزامی است"}));const before=(await query("SELECT * FROM warning_cases WHERE group_id=$1 AND user_id=$2 LIMIT 1",[groupId,userId])).rows[0];if(!before||Number(before.warning_count||0)===0)return send(res,404,JSON.stringify({error:"اخطار فعال برای این کاربر وجود ندارد"}));const result=await query("UPDATE warning_events SET status='cleared',result='cleared' WHERE group_id=$1 AND user_id=$2 AND action_type='warning' AND status='active' RETURNING id",[groupId,userId]);await query("UPDATE warning_cases SET warning_count=0,current_level=0,status=CASE WHEN EXISTS(SELECT 1 FROM warning_penalties WHERE group_id=$1 AND user_id=$2 AND status='active') THEN 'penalized' ELSE 'cleared' END,updated_at=NOW() WHERE group_id=$1 AND user_id=$2",[groupId,userId]);const actorId=cleanText(body.admin_id||"PANEL_OWNER",120),actorName=cleanText(body.admin_name||"مدیر پنل",120),ev=(await query("INSERT INTO warning_events(group_id,user_id,first_name,username,action_type,message_fa,admin_id,admin_name,status,result) VALUES($1,$2,$3,$4,'clear','تمام اخطارهای فعال این کاربر پاک شد.',$5,$6,'cleared','completed') RETURNING *",[groupId,userId,before.first_name,before.username,actorId,actorName])).rows[0];await audit("warning_cleared",actorId,groupId,before,{cleared:result.rowCount});return send(res,200,JSON.stringify({success:true,event:ev}));}
    if(req.method==="POST"&&url.pathname==="/api/warnings/penalty"){const body=await readBody(req),groupId=validId(body.group_id),userId=validId(body.user_id),type=String(body.penalty_type||"mute");if(!groupId||!userId)return send(res,400,JSON.stringify({error:"group_id and user_id are required"}));const duration=durationValue(body.duration_value,null),unit=String(body.duration_unit||"hours"),check=penaltyCheck(type,duration,type==="permanent_ban"?null:unit);if(check)return send(res,400,JSON.stringify({error:check}));const actorId=cleanText(body.admin_id||"PANEL_OWNER",120),actorName=cleanText(body.admin_name||"مدیر پنل",120),reason=cleanText(body.reason||"جریمه دستی",500),firstName=cleanText(body.first_name||"",160),username=cleanText(body.username||"",160);await query("INSERT INTO warning_cases(group_id,user_id,first_name,username) VALUES($1,$2,$3,$4) ON CONFLICT(group_id,user_id) DO UPDATE SET first_name=COALESCE(NULLIF($3,''),warning_cases.first_name),username=COALESCE(NULLIF($4,''),warning_cases.username),updated_at=NOW()",[groupId,userId,firstName,username]);const ev=(await query("INSERT INTO warning_events(group_id,user_id,first_name,username,action_type,violation_type,custom_violation,penalty_type,duration_value,duration_unit,admin_id,admin_name,status,result) VALUES($1,$2,$3,$4,'penalty','جریمه دستی',$5,$6,$7,$8,$9,$10,'pending','queued') RETURNING *",[groupId,userId,firstName,username,reason,type,duration,type==="permanent_ban"?null:unit,actorId,actorName])).rows[0],penalty=(await query("INSERT INTO warning_penalties(group_id,user_id,event_id,penalty_type,duration_value,duration_unit,reason,admin_id,admin_name,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'pending') RETURNING *",[groupId,userId,ev.id,type,duration,type==="permanent_ban"?null:unit,reason,actorId,actorName])).rows[0];await query("INSERT INTO warning_action_queue(group_id,user_id,event_id,penalty_id,action_type,penalty_type,duration_value,duration_unit,status) VALUES($1,$2,$3,$4,'penalty_apply',$5,$6,$7,'pending')",[groupId,userId,ev.id,penalty.id,type,duration,type==="permanent_ban"?null:unit]);await query("UPDATE warning_cases SET status='penalized',updated_at=NOW() WHERE group_id=$1 AND user_id=$2",[groupId,userId]);await audit("penalty_manual",actorId,groupId,null,{user_id:userId,penalty_type:type,duration,duration_unit:unit});return send(res,201,JSON.stringify({success:true,event,penalty}));}
    return null;
  }catch(error){console.error("[warnings] API error:",error.message);return send(res,500,JSON.stringify({error:error.message||"Warning API error"}));}
}
module.exports={ensureWarningsSchema,warningsApi};